### ISSUE TITLE
Documentacion con campos repetidos?

### ISSUE THREAD

**Issue by florvarise** [EL-BID/UrbanTrips#113]
![Screenshot 2023-10-09 190616](https://github.com/EL-BID/UrbanTrips/assets/62365733/4c3c54bc-32a3-4eb6-a52a-001ac93dfa1d)

Hola! Los primeros dos campos entiendo que hacen referencia a lo mismo.

**Comment by alephcero** [comment]
Gracias por el reporte! Resuelto 9c42869d60a43a2597dd33b18aa469611792ffdc
