### ISSUE TITLE
Chequeo de configuraciones_generales.yaml

### ISSUE THREAD

**Issue by sanapolsky** [EL-BID/UrbanTrips#2]
Habría que chequear que las variables existan en el archivo de transacciones (o que nombres coincidas con la configuración). En utils agregué una función check_config(), deberíamos pensar en usarla al principio y si no pasa que el proceso no siga. Aca mismo podríamos chequear el formato de fecha. Tanto nombre de variables como formato fecha son errores comunes cuando probamos distintas ciudades.

**Comment by alephcero** [comment]
Closed by https://github.com/EL-BID/UrbanTrips/commit/881d0ff295c8f270887f879d9e131e6aaa48dcd6
